  CREATE TABLE ACCOUNT_INFO(
  ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
  BALANCE               BIGINT,
  PASSWORD              VARCHAR (200)
);

CREATE TABLE TRANSFER_OPERATION(
  ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
  AMOUNT                BIGINT,
  SENDER_ID             BIGINT,
  RECEIVER_ID           BIGINT,
  OPERATION_DATE         TIMESTAMP
);

INSERT INTO ACCOUNT_INFO VALUES (0, 100000, '$2a$10$5Y7CWN0Qb7AtzqYYA/VAceDxZ68JWYhlOQ7dYoiyvWlRi3Dqy.Sme');
INSERT INTO ACCOUNT_INFO VALUES (1, 100000, '$2a$10$5Y7CWN0Qb7AtzqYYA/VAceDxZ68JWYhlOQ7dYoiyvWlRi3Dqy.Sme');